---
# ============================================
# ⚠️ Important Note:
# This file usually does not need to be edited.
# All configuration and customization should be done
# in the .env file (e.g. ports, paths, user IDs).
# ============================================

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${PLEX_CONFIG}:/config
      - ${PATH_TV}:/tv
      - ${PATH_MOVIES}:/movies
    ports:
      - "32400:32400"
    restart: always
    networks:
      - net_homeflix

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${OVERSEERR_CONFIG}:/config
    ports:
      - "5055:5055"
    restart: always
    networks:
      - net_homeflix

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${PATH_MOVIES}:/movies
      - ${PATH_DOWNLOADS}:/downloads
    restart: always
    networks:
      - net_homeflix

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${PATH_TV}:/tv
      - ${PATH_DOWNLOADS}:/downloads
    restart: always
    networks:
      - net_homeflix

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${SABNZBD_CONFIG}:/config
      - ${PATH_INCOMPLETE}:/incomplete-downloads
      - ${PATH_DOWNLOADS}:/downloads
    restart: always
    networks:
      - net_homeflix

# Networks
networks:
  net_homeflix:
    name: net_homeflix
    driver: bridge
